In [1]:
import	numpy	as	np
import	pandas	as	pd
import csv
from service import Storage as stor

#	Set	some	pandas	options	for	controlling	output
pd.set_option('display.notebook_repr_html',	False)
pd.set_option('display.max_columns',	10)
pd.set_option('display.max_rows',	10)

In [2]:
path = '/home/nidia/Documents/UFC/Doutorado/2018/predicao/dados/' \
       'CAJU-dados_solo_metereologico_estacao_INMET_2016_2017_2018.csv'

database = stor.Storage('localhost', 'root', '12345678')

# with open(path, mode='r') as csv_file:
#     csv_reader = csv.DictReader(csv_file)
# 
#     data = ""
#     date = ""
#     T_max=0
#     T_min=0
#     RH_max=0
#     RH_min=0
#     Rn=0
#     P=0
#     U=0
#     Ri=0
#     
#     for row in csv_reader:
#         data = row["Data"].split('/')
#         date = data[2] + "-" + data[1] + "-" + data[0] + " 00:00:00"
#         
#         try:
#             T_max=float(row["T_max"])            
#         except ValueError as e:
#             T_max=None
# 
#         try:
#             T_min=float(row["T_min"])            
#         except ValueError as e:
#             T_min=None
# 
#         try:
#             RH_max=float(row["RH_max"])            
#         except ValueError as e:
#             RH_max=None
# 
#         try:
#             RH_min=float(row["RH_min"])            
#         except ValueError as e:
#             RH_min=None
#         
#         try:
#             Rn=float(row["Rn"])            
#         except ValueError as e:
#             Rn=None
# 
#         try:
#             U=float(row["U2"])            
#         except ValueError as e:
#             U=None
# 
#         try:
#             P=float(row["P"])            
#         except ValueError as e:
#             P=None
# 
#         try:
#             Ri=float(row["Ri_f"])            
#         except ValueError as e:
#             Ri=None
# 
#         
#         database.insert_meteorological_data(station_id=1, date=date, T_max=T_max,
#                                             T_min=T_min, RH_max=RH_max,
#                                             RH_min=RH_min, Rn=Rn, U=U,
#                                             P=P,Ri=Ri)

In [3]:
#inserir usuarios
# id = database.insert_user_type("agronomo", "engenheiro agronomo")
# user_id = database.insert_user("rubens_sonsol", id)

In [4]:
#inserir fazenda
#farm_id = database.insert_farm(latitude=3.5,longitude=39,altitude=20,user_id=user_id,meteorological_station_id=1)

In [5]:
#inserir cultivo
#crop_id=database.insert_crop_type("caju anao",300,700, 1300, 
#                                  0.6, 1, 1,60)

In [6]:
#irrigation_type_id = database.insert_irrigation_system_type(
#     "microaspersao", "sistema de microaspers√£o")
# 
# 
# irrigation_system_id = database.insert_irrigation_system(
#     irrigation_type_id, 0.8185, 12.5)

In [7]:
#inserir campo
#field_id=database.insert_field(farm_id,crop_id,300,300,irrigation_system_id)

In [8]:
#inserir pontos de monitoramento do campo
# database.insert_monitoring_point(1, field_id)
# database.insert_monitoring_point(2, field_id)
# database.insert_monitoring_point(3, field_id)
# database.insert_monitoring_point(4, field_id)
# database.insert_monitoring_point(5, field_id)
# database.insert_monitoring_point(6, field_id)
# database.insert_monitoring_point(7, field_id)
# database.insert_monitoring_point(8, field_id)
# database.insert_monitoring_point(9, field_id)

In [9]:
#inserir camadas do solo
# layers_ids = []
# for i in range(1,10):
#     layer_15_id=database.insert_soil_layer(150,20,i,1,0.14010,0.38839,0.022504,20.524)
#     layer_45_id=database.insert_soil_layer(450,20,i,1,0.14010,0.38839,0.022504,20.524)
#     layer_75_id=database.insert_soil_layer(750,20,i,1,0.14010,0.38839,0.022504,20.524)
#     layers_ids.append([layer_15_id[0],layer_45_id[0],layer_75_id[0]])
#     
# 
# print("layers ids {}".format(layers_ids))

In [10]:
# field_id=1
# with open(path, mode='r') as csv_file:
#     csv_reader = csv.DictReader(csv_file)
# 
#     data = ""
#     date = ""
#     T1_15=0
#     T1_45=0
#     T1_75=0
#     T2_15=0
#     T2_45=0
#     T2_75=0
#     T3_15=0
#     T3_45=0
#     T3_75=0
#     T4_15=0	
#     T4_45=0
#     T4_75=0
#     T5_15=0
#     T5_45=0
#     T5_75=0
#     T6_15=0
#     T6_45=0
#     T6_75=0
#     T7_15=0	
#     T7_45=0
#     T7_75=0
#     T8_15=0	
#     T8_45=0
#     T8_75=0	
#     T9_15=0	
#     T9_45=0
#     T9_75=0
# 
# 
#     for row in csv_reader:
#         data = row["Data"].split('/')
#         date = data[2] + "-" + data[1] + "-" + data[0] + " 00:00:00"
# 
#         try:
#             T1_15=float(row["T1-15"])            
#         except ValueError as e:
#             T1_15=None
# 
#         try:
#             T2_15=float(row["T2-15"])            
#         except ValueError as e:
#             T2_15=None
# 
#         try:
#             T3_15=float(row["T3-15"])            
#         except ValueError as e:
#             T3_15=None
# 
#         try:
#             T4_15=float(row["T4-15"])            
#         except ValueError as e:
#             T4_15=None
# 
#         try:
#             T5_15=float(row["T5-15"])            
#         except ValueError as e:
#             T5_15=None
# 
#         try:
#             T6_15=float(row["T6-15"])            
#         except ValueError as e:
#             T6_15=None
# 
#         try:
#             T7_15=float(row["T7-15"])            
#         except ValueError as e:
#             T7_15=None
# 
#         try:
#             T8_15=float(row["T8-15"])            
#         except ValueError as e:
#             T8_15=None
# 
#         try:
#             T9_15=float(row["T9-15"])            
#         except ValueError as e:
#             T9_15=None
# 
# 
#         try:
#             T1_45=float(row["T1-45"])            
#         except ValueError as e:
#             T1_45=None
# 
#         try:
#             T2_45=float(row["T2-45"])            
#         except ValueError as e:
#             T2_45=None
# 
#         try:
#             T3_45=float(row["T3-45"])            
#         except ValueError as e:
#             T3_45=None
# 
#         try:
#             T4_45=float(row["T4-45"])            
#         except ValueError as e:
#             T4_45=None
# 
#         try:
#             T5_45=float(row["T5-45"])            
#         except ValueError as e:
#             T5_45=None
# 
#         try:
#             T6_45=float(row["T6-45"])            
#         except ValueError as e:
#             T6_45=None
# 
#         try:
#             T7_45=float(row["T7-45"])            
#         except ValueError as e:
#             T7_45=None
# 
#         try:
#             T8_45=float(row["T8-45"])            
#         except ValueError as e:
#             T8_45=None
# 
#         try:
#             T9_45=float(row["T9-45"])            
#         except ValueError as e:
#             T9_45=None
# 
#         try:
#             T1_75=float(row["T1-75"])            
#         except ValueError as e:
#             T1_75=None
# 
#         try:
#             T2_75=float(row["T2-75"])            
#         except ValueError as e:
#             T2_75=None
# 
#         try:
#             T3_75=float(row["T3-75"])            
#         except ValueError as e:
#             T3_75=None
# 
#         try:
#             T4_75=float(row["T4-75"])            
#         except ValueError as e:
#             T4_75=None
# 
#         try:
#             T5_75=float(row["T5-75"])            
#         except ValueError as e:
#             T5_75=None
# 
#         try:
#             T6_75=float(row["T6-75"])            
#         except ValueError as e:
#             T6_75=None
# 
#         try:
#             T7_75=float(row["T7-75"])            
#         except ValueError as e:
#             T7_75=None
# 
#         try:
#             T8_75=float(row["T8-75"])            
#         except ValueError as e:
#             T8_75=None
# 
#         try:
#             T9_75=float(row["T9-75"])            
#         except ValueError as e:
#             T9_75=None
# 
#        
#         database.insert_moisture_data(date,field_id,layers_ids[0][0],1,T1_15)
#         database.insert_moisture_data(date,field_id,layers_ids[1][0],2,T2_15)
#         database.insert_moisture_data(date,field_id,layers_ids[2][0],3,T3_15)
#         database.insert_moisture_data(date,field_id,layers_ids[3][0],4,T4_15)
#         database.insert_moisture_data(date,field_id,layers_ids[4][0],5,T5_15)
#         database.insert_moisture_data(date,field_id,layers_ids[5][0],5,T6_15)
#         database.insert_moisture_data(date,field_id,layers_ids[6][0],7,T7_15)
#         database.insert_moisture_data(date,field_id,layers_ids[7][0],8,T8_15)
#         database.insert_moisture_data(date,field_id,layers_ids[8][0],9,T9_15)
#         
#         database.insert_moisture_data(date,field_id,layers_ids[0][1],1,T1_45)
#         database.insert_moisture_data(date,field_id,layers_ids[1][1],2,T2_45)
#         database.insert_moisture_data(date,field_id,layers_ids[2][1],3,T3_45)
#         database.insert_moisture_data(date,field_id,layers_ids[3][1],4,T4_45)
#         database.insert_moisture_data(date,field_id,layers_ids[4][1],5,T5_45)
#         database.insert_moisture_data(date,field_id,layers_ids[5][1],5,T6_45)
#         database.insert_moisture_data(date,field_id,layers_ids[6][1],7,T7_45)
#         database.insert_moisture_data(date,field_id,layers_ids[7][1],8,T8_45)
#         database.insert_moisture_data(date,field_id,layers_ids[8][1],9,T9_45)
#         
#         database.insert_moisture_data(date,field_id,layers_ids[0][2],1,T1_75)
#         database.insert_moisture_data(date,field_id,layers_ids[1][2],2,T2_75)
#         database.insert_moisture_data(date,field_id,layers_ids[2][2],3,T3_75)
#         database.insert_moisture_data(date,field_id,layers_ids[3][2],4,T4_75)
#         database.insert_moisture_data(date,field_id,layers_ids[4][2],5,T5_75)
#         database.insert_moisture_data(date,field_id,layers_ids[5][2],5,T6_75)
#         database.insert_moisture_data(date,field_id,layers_ids[6][2],7,T7_75)
#         database.insert_moisture_data(date,field_id,layers_ids[7][2],8,T8_75)
#         database.insert_moisture_data(date,field_id,layers_ids[8][2],9,T9_75)

In [11]:
#insert irrigation management type
database.insert_irrigation_management_type("Turno_Rega","manejo do turno de rega")
database.insert_irrigation_management_type("Hydro_Balance","manejo do balan√ßo hidrico")
database.insert_irrigation_management_type("Matric_Potential","manejo do potencial matrico")
irr_man_id=database.insert_irrigation_management_type("Salvation_Irrigation","irriga√ß√£o de salva√ß√£o-experimento")

In [14]:
field_id=1
monitoring_points_ids = database.get_monitoring_points(field_id)

with open(path, mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        data = row["Data"].split('/')
        date = data[2] + "-" + data[1] + "-" + data[0] + " 00:00:00"
        for mp_id in monitoring_points_ids:
            if mp_id==1:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W1"],date)
            elif  mp_id==2:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W2"],date)
            elif  mp_id==3:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W3"],date)
            elif  mp_id==4:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W4"],date)
            elif  mp_id==5:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W5"],date)
            elif  mp_id==6:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W6"],date)
            elif  mp_id==7:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W7"],date)
            elif  mp_id==8:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W8"],date)
            elif  mp_id==9:
                database.insert_irrigation_management(farm_id,mp_id,irri_man_id,row["W9"],date)

NameError: name 'farm_id' is not defined